### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by Ravyar19** [murtaja1/find_yours#1]
![Navbar](https://user-images.githubusercontent.com/60940388/111496051-fe638300-8750-11eb-957d-ddc91d64552a.PNG)

**Comment by Ravyar19** [comment]
**Please use Oswald(bold) font**

**Comment by Othmanosx** [comment]
I'm done with the Navbar component, check commit 6beb41be0fd2f0eb0018a4299813e8f5e4686817
